server:
  port: 8080

spring:

  main:
    web-application-type: reactive

  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:

          discovery:
            locator:
              enabled: true

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/v*/users/**, /springdoc/openapi3-user-service.json

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/v*/orders/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/v*/products/**

            - id: vendor-service
              uri: lb://vendor-service
              predicates:
                - Path=/v*/vendors/**

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/v*/hubs/**

            - id: hub-path-service
              uri: lb://hub-path-service
              predicates:
                - Path=/v*/hub-paths/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/v*/deliveries/**

            - id: delivery-path-service
              uri: lb://delivery-path-service
              predicates:
                - Path=/v*/delivery-paths/**, /springdoc/openapi3-delivery-path-service.json

            - id: slack-service
              uri: lb://slack-service
              predicates:
                - Path=/v*/slacks/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

springdoc:
  swagger-ui:
#    urls[0]:
#      name: user-service
#      url: /springdoc/openapi3-user-service.json
    urls[0]:
      name: delivery-path-service
      url: /springdoc/openapi3-delivery-path-service.json
    #    use-root-path: true
    path: /docs